# Module 12: Modeling + Machine Learning with Python Libraries

- A typical workflow for model development in Python relies on Pandas for data loading and cleaning followed by use of a modeling library to construct the actual model. 


- The specific Python library you choose to make use of is often dependent upon the type of model you are planning to construct: while many Python modeling libraries provide similar capabilities, it is up to you as an analytics practitioner to select the library that you believe is appropriate for the task at hand.


- Prior to constructing a model, it is oftentimes beneficial to consider the addition of new attributes (or "features") to your data that you believe will either simplify or enhance the performance of your intended model. We create such "features" through the use of the __domain knowledge__ we have for the data we plan to make use of.


- The addition of new attributes/features based on __domain knowledge__ is referred to as __Feature Engineering__.


## Feature Engineering

What is a __"feature"__? In general, a __feature__ is an attribute or property shared by all of the independent variables we are planning to use for purposes of analysis or model building.

In general, we can think of __feature engineering__ as creating new attributes for modeling based on both our __domain knowledge__ and the data we already have at hand.

Some examples of __feature engineering__:

- __Creation of indicator variables based on your domain knowledge__: For example, if we were working with historical data on US housing prices for the years 2000 - 2018, our domain knowledge could tell us that a major collapse in US housing prices occurred during the 2007 - 2012 timeframe due to the 2007 financial crisis, followed by a recovery that started during the year 2012. As such, if we believe that our overall housing price data content may have been tangibly impacted by the financial crisis, we could create a binary indicator variable that flags every data item within the 2007-2012 time period as potentially having been impacted by the financial crisis (assigning a '1' as the indicator), while all other data items are assigned a '0' for the indicator variable's value.


- __Create "Interaction" Features__: Interaction features are new metrics we __derive__ from our existing data (NOTE: we've already touched on this concept this semester).Examples include creating new ratios / proportions from our existing data as well as binning / bucketing of numeric data and the de-structuring of date / time values.


- __Combining Sparse Classifications__: With categorical data, "sparse classes" are those that have very few observations within a data set. Such "sparse data" can cause problems with a wide variety of predictive and machine learning models (e.g., causing the models to "overfit" the data use for model training purposes).  These challenges can oftentimes be overcome by combining sparse classes into new classifications that aggregate the sparse items based on some shared characteristic(s). How you identify such "shared characteristics" is highly subjective, i.e., you need to apply your __domain knowledge__ to identify them. 


- __Adding "Dummy" Variables__: As we've previously discussed, we cannot use raw categorical data as input to a model that requires numerical data. Instead, we create a new "0/1" binary indicator variable for each categorical data value.


- __Removal of Unused Attributes/Features__: Oftentimes our data sets contain attributes that are of no use whatsoever for modeling purposes, such as unique ID's, text descriptions, and any other data that may be unlikely to be available if the model were placed into a "production" environment. Such attributes should be removed from the data you plan to use as input to a model.


### How to Approach Feature Engineering?

1. Using your __domain knowledge__, brainstorm ideas for potential new features relative to the data you have at hand.


2. Create the features you believe will be useful (i.e., figure out how to add them to your data set).


3. Test the features within your proposed analysis/model: do they improve the performance of the model? How relevant are they to the data set, i.e., do they provide new information that isn't available in any other attribute/feature already contained in the data set? Are they duplicative/redundant relative to other features/attributes contained within the data set? etc.


4. Refine/improve your new features if needed.


5. Go back to Step 1 (above) and consider whether the addition of other features would be beneficial.

## Regression Modeling

In general, the phrase __regression modeling__ refers to the process of estimating the strength of the relationship between one variable (the __"Response" (aka "Dependent") variable__) and one or more __"Explanatory" (aka "Independent") variables__. 


Regression modeling is widely used for purposes of __predicting the mean numerical value of the response variable__ when given specific values for the explanatory variables.


There are many different types of regression models, and the characteristics of each vary depending on the type of response variable you are attempting to estimate. Some of the most widely used types of regression models include:

- __Linear Regression__: Used for fitting a linear equation for a __continuous__ numeric response variable. The relationship between the response and explanatory variable(s) is assumed to be __linear__ in nature. The output is a __linear equation__. If there is only one explanatory variable, we use __Simple Linear Regression__. If there is more than one explanatory variable, we use __Multiple Linear Regression__.


- __Polynomial Regression__: Used when a __non-linear__ relationship exists between a continuous response variable and explanatory variables that are either binary, discrete or continuous. The ouput is a __non-linear__ equation.


- __Binary Logistic Regression__: The response variable is a __binary categorical variable__, while the explanatory variables can be either continuous, discrete or binary (e.g., dummy variables created from the values of a categorical variable).


- __Multinomial Logistic Regression (MLR)__: The response variable is a categorical variable having __more than two (2) possible values__, while the explanatory variables can be either continuous, discrete or binary. There are many types of MLR models, and the exact type of MLR model you choose to use will be dependent on whether your response variable is __ordinal__ or __nominal__ in nature.


- __"Count" Regression__: The response variable contains __non-negative__ (i.e., x >= 0) __discrete__ numeric "count" values while the explanatory variables can be either binary, discrete or continuous. Commonly used regression techniques for modeling count data include __Poisson Regression__ (where the response variable __must__ have a Poisson distribution), __Negative Binomial Regression__ (where the response variable need not have a Poisson distribution), and __Zero-Inflated Negative Binomial Regression__ (used when the response variable contains an excessive number of 'zero' values).


\*\* Please note that there are __many__ other types of regression models (e.g., Lasso, Ridge, Partial Least Squares, etc.), and describing each of them is beyond the scope of this lecture.\*\*


### Linear Regression

Linear regression consists of finding the best fitting straight line through a set of data points. That line is called a __regression line__. An example:

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [7]:

# generate some random data to use for the plot
x = np.random.randn(50) * 10

y = np.random.randn(50) * 10

# first define a Matplotlib figure
plt.figure()
# use Seaborn's regplot() function to plot the regression line for the 
sns.regplot(x, y)

# give the plot a title using Matplotlib
plt.title('Regression Plot');

Simple linear regression equations take the form of 
$y' = bx + a$ where $y'$ is the predicted value of the response variable for a given value of the explanatory variable $x$, $b$ is the slope of the regression line, $x$ is the value of the explanatory variable and $a$ is a constant representing the y-intercept of the regression line. 


The regression line is created by using the known values of the explanatory variable $x$ and the known values of the response variable $y$ to find the slope $b$ and y-intercept $a$ of the line that minimizes the sum of the squared errors of the predicted values of $y'$. 


We calculate values for the slope $b$ and the y-intercept $a$ using the means and standard deviations of the known values of $x$ and $y$ as well as the correlation coefficient $r$ of $x$ and $y$:

$b = r * stddev(y)/stddev(x) $

$a = mean(y) - b(mean(x))$

__NOTE:__ The Python modeling libraries we are discussing below do these calculations for you. The calculations are shown here simply to provide further context.

A simple linear regression example:

http://onlinestatbook.com/2/regression/intro.html



### Multiple Linear Regression

When using multiple explanatory variables, the regression line __cannot be visualized within a two-dimensional space__. However, it is still relatively easy to compute: the regression line is estimated using the formula

$y' = a + b1x1 + b2x2 + .. +bnxn$


where $y'$ is the predicted value for the response variable for given values of the explanatory variables x1, x2, .., xn, and the $b$ values represent the __independent contributions__ of the corresponding explanatory variable to the prediction of the response variable.  

For those who desire further explanation of the underlying mathematics:

http://faculty.cas.usf.edu/mbrannick/regression/Reg2IV.html


### Binary Logistic Regression

In binary logistic regression, the response variable is __binary__, i.e., it contains data encoded as either '1' (e.g., 'True') or '0' (e.g., 'False'). In other words, logistic regression is used for __classification__ problems.

Logistic regression finds the best fitting __mathematical model__ (not a simple linear equation) to describe the relationship between the binary response variable and the explanatory variable(s). The values it generates are the coefficients of a formula to predict a __logit transformation__ (aka "__log odds"__) which is the logarithm of the odds $p$ of the propability of the presence of the characteristic of interest. 

$logit(p) = ln(p/(1-p)) = b0 + b1x1 + b2x2 + .. + bnxn$

where $p$ = the probability of the __presence__ of a characteristic,

$(1-p)$ = the probability of the __abscence__ of a characteristic,

$b0$ = is a constant value

$b1, b2, ..,bn$ = the regression coefficients for the explanatory variables $x1, x2, .., xn$

Further explanation is available here:

https://www.statisticssolutions.com/what-is-logistic-regression/


While a wide variety of statistical modeling libraries are available for use within __Python__, we will limit our focus to those mentioned in the PfDA text: __Patsy__, __statsmodels__, and __scikit-learn__. (__NOTE__: All three of these libraries are usually provided automatically when you install __Anaconda__.)

## Patsy: A Python Library for Describing Statistical Models

- Most often used for describing linear models.


- Uses a simple syntactical structure.


- Developed to mimic the way in which the R and S programming languages allow a user to specify linear models + models that have a linear component.


- Basic approach is: 1) create a formula string, e.g., 'y ~ x0 + x1' based on the contents of a data set; 2) use patsy.dmatrices() to generate the design matrix for a linear model. The resulting "dmatrix" is then fed into a pre-built statistical modeling function from a library such as __statsmodels__.


- Some examples are provided in the PfDA text

## statsmodels: A Python Library for Fitting Many Types of Statistical Models

__statsmodels__ contains tools for performing statistical tests, data exploration and visualization, and supports many types of statistical models including:

- Linear models, generalized linear models, logistic regression, robust linear models, etc.

- ANOVA (Analysis of Variance) models

- Time series modeling


Let's take a look at __statsmodels'__ linear modeling tools.


### Linear Models with statsmodels

- __statsmodels__ supports many kinds of linear regression models, including ordinary least squares.


- Linear models are specified in __statsmodels__ either via arrays or formulas.


__An example__: A multiple linear model specified via arrays using some random data. First, let's implement the model using linear algebra/matrix mathematics (i.e., without using __statsmodels__):

In [8]:
# import numpy, pandas
import numpy as np
import pandas as pd

# import statsmodels
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [14]:
# dnorm is a function used to generate normally distributed data having
# a particular mean and variance
def dnorm(mean, variance, size=1):
    # check to ensure size is an integer
    if isinstance(size, int):
        size = size,
    # now generate an array of size 'size' where each item is sampled from
    # a normal distribution, multiplied by the provided variance and then
    # has the provided mean value added to it
    return mean + np.sqrt(variance) * np.random.randn(*size)

# For reproducibility, we set the random generator seed to a fixed value
np.random.seed(12345)

# define the number of items we want to have in our data set
N = 100

# np.c_ is a 'concatenate' method, so we are concatenating 3 1 dimensional
# arrays of size 'N'. So we have 3 explanatory variables in our X array
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]

# let's take a look at the first 5 rows of X
X[:5]

array([[-0.12946849, -1.21275292,  0.50422488],
       [ 0.30291036, -0.43574176, -0.25417986],
       [-0.32852189, -0.02530153,  0.13835097],
       [-0.35147471, -0.71960511, -0.25821463],
       [ 1.2432688 , -0.37379916, -0.52262905]])

In [16]:
# eps is an array of random error terms for our linear equation: must be same
# size as the arrays we created above
eps = dnorm(0, 0.1, size=N)

# beta is our set of coefficients for the three explanatory variables
beta = [0.1, 0.3, 0.5]

# now define our linear equation by adding our random error 'eps' to
# the dot product of array 'X' and array 'Beta'; the results in variable 
# 'y' are our estimated values/output of our linear equation
y = np.dot(X, beta) + eps

In [17]:
# now what is 'X'? It is an array containing 100 rows ('N' == 100) of 
# 3 columns of random data
X.shape

(100, 3)

In [6]:
# what is 'y'? It is an array containing the results of our 
# linear estimation equation: np.dot(X, beta) + eps
y.shape

(100,)

In [20]:
# check the corresponding elements of arrays 'X' and 'y'
print(X[[5]])
print(' ')

# array y contains the predicted values
print(y[5])

[[ 0.88126723 -0.02808985 -0.36896015]]
 
0.07423798034615169


In [19]:
# now apply the linear equation we defined above to X[[5]] to see if the result
# matches the content of y[5]
np.dot(X[[5]], beta) + eps[5]

array([0.07423798])

In the above example, we are modeling $y' = (b1x1 + \epsilon) + (b2x2 + \epsilon).. + (bnxn + \epsilon)$ where the $b$ values represent the __independent contributions__ of the corresponding explanatory variable to the prediction of the response variable, and $\epsilon$ is the random error we add to each term. __What's missing__?

__We are missing an intercept value__. The general form of a multiple linear model is $y' = a + b1x1 + b2x2 + .. +bnxn$ where $a$ is the intercept value. So we would need to further refine our example by adding a value for the intercept. 

Furthermore, __we usually do not know the coefficients for the explanatory variables beforehand__ (the contents of the 'beta' array in this example).

Now let's look at an example of how __statsmodels'__ ordinary least squares ('OLS()') function can estimate the regression coefficients for us. We need to start by adding a constant 'intercept' value to our array 'X':

In [13]:
# add an intercept value to the array 'X' we've defined
X_model = sm.add_constant(X)
X_model[:5]

array([[ 1.        , -0.12946849, -1.21275292,  0.50422488],
       [ 1.        ,  0.30291036, -0.43574176, -0.25417986],
       [ 1.        , -0.32852189, -0.02530153,  0.13835097],
       [ 1.        , -0.35147471, -0.71960511, -0.25821463],
       [ 1.        ,  1.2432688 , -0.37379916, -0.52262905]])

In [15]:
# now instead of using np.dot, use statsmodels' OLS() function to fit
# an ordinary least squares regression equation to our random data
model = sm.OLS(y, X)

# now get the results of the regression
results = model.fit()

# check the regression coefficients for our 3 explanatory variables (X1, X2, X3)
results.params

array([0.17826108, 0.22303962, 0.50095093])

In [16]:
# print the detailed diagnostic data for the model
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.430
Model:                            OLS   Adj. R-squared:                  0.413
Method:                 Least Squares   F-statistic:                     24.42
Date:                Fri, 22 Mar 2019   Prob (F-statistic):           7.44e-12
Time:                        17:15:35   Log-Likelihood:                -34.305
No. Observations:                 100   AIC:                             74.61
Df Residuals:                      97   BIC:                             82.42
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.1783      0.053      3.364      0.0

#### Intepreting the Model Statistics from Statsmodels' OLS() Function
- $R^2$: Often referred to as "Goodness of fit"; measures how much of the variation in the response variable $y'$ is explained by variation in the explanatory variable(s). In general, __the larger the value of $R^2$, the more accurate the model is__. However, relatively large values of $R^2$ can also be an indication of the model being "overfit" to the training data.


- __Adjusted__ $R^2$: Increases if a new variable added to the model improves the fit of the model by more than would be expected by sheer chance. When comparing two models derived from the same data, models with __higher__ __Adjusted__ $R^2$ scores are preferable to those having relatively lower scores. 


- __AIC__: Akaike Information Criteria is a model selection metric that estimates the relative quality of a statistical model for a given set of data. When comparing two models derived from the same data, models with __lower__ __AIC__ scores are preferable to those having relatively higher scores.


- __BIC__: Bayesian Information Criteria is another model selection metric that estimates the unexplained variation in the response variable relative to the given explanatory variables. __BIC__ also imposes a "complexity" penalty when the number of explanatory variables used is increased.  When comparing two models derived from the same data, models with __lower__ __BIC__ scores are preferable to those having relatively higher scores.


- __F Statistic__: Indicates whether a significant amount of variance in the response variable $y'$ is explained by the model. When comparing two models derived from the same data, models with __higher__ __F Statistic__ scores are preferable to those having relatively lower scores. 


- __Log Likelihood__: A measure of how well a model fits the underlying data. When comparing two models derived from the same data, models with __higher__ __Log Likelihood__ scores are preferable to those having relatively lower scores. 


- __p values__: Measure the statistical significance of the explanatory variables in your model. While you are free to select the significance level on your own, most often 0.05 is used as the maximum bound for significance. As such, if any variable in your model is shown to have a __p value__ that exceeds 0.05, consider removing it from the model to see whether the fit/model selection metrics improve.


#### What if our data is instead contained within a Pandas DataFrame? 

Note that the above example has assumed our data is contained within a numpy array. What if the data is instead housed within a Pandas DataFrame?

One crucial difference is that __we do not need to add a constant value for the intercept if our data is contained within a DataFrame__:

In [17]:
# define a data frame containing our 3 explanatory variables
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])

# add our response variable to the data frame
data['y'] = y
data[:5]

col0      col1      col2         y
0 -0.129468 -1.212753  0.504225  0.427863
1  0.302910 -0.435742 -0.254180 -0.673480
2 -0.328522 -0.025302  0.138351 -0.090878
3 -0.351475 -0.719605 -0.258215 -0.489494
4  1.243269 -0.373799 -0.522629 -0.128941

In [18]:
# Use the statsmodel/Patsy 'formula' api to specify the linear model:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()
results.params

Intercept    0.033559
col0         0.176149
col1         0.224826
col2         0.514808
dtype: float64

In [20]:
# check the t-value of 
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.435
Model:                            OLS   Adj. R-squared:                  0.418
Method:                 Least Squares   F-statistic:                     24.68
Date:                Fri, 22 Mar 2019   Prob (F-statistic):           6.37e-12
Time:                        17:33:43   Log-Likelihood:                -33.835
No. Observations:                 100   AIC:                             75.67
Df Residuals:                      96   BIC:                             86.09
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0336      0.035      0.952      0.3

### Case Study: Linear Regression with statsmodels

https://github.com/justmarkham/DAT4/blob/master/notebooks/08_linear_regression.ipynb

## scikit-learn: A General-Purpose Machine Learning Toolkit

__scikit-learn__ contains tools for machine learning tasks such as classification, clustering and prediction as well as for modeling tasks such as model selection & evaluation, data transformation and data loading 

Like __statsmodels__, __scikit-learn__ is widely used and is considered to be a reliable and robust modeling library.


### Logistic Regression example with scikit-learn

From the PfDA text: Use the 'Titanic' data set which contains passenger survival rate data for the ocean-going vessel of that name that sank in 1912. 

Our goal is to __try to predict whether or not a passenger would have been more likely than not to survive the sinking of the Titanic__ based on the data contained in the data set (i.e., build a __predictive model__).

- First, we will fit a logistic regression model on a __training__ data set using the data set's __PClass__, __Age__, and __Sex__ attributes.


- Then we evaluate the model using a __testing__ data set that is exclusive of the data contained in the __training__ data set.


In [3]:
# load the LogisticRegression() function from sklearn's 'linear_model' sub-library
from sklearn.linear_model import LogisticRegression

# load the training + testing data sets for the Titanic data
train = pd.read_csv('https://raw.githubusercontent.com/wesm/pydata-book/2nd-edition/datasets/titanic/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/wesm/pydata-book/2nd-edition/datasets/titanic/test.csv')

# display the first four rows of the data set
train[:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [21]:
# lets check the first four rows of the test data
# Note the lack of a "Survived" indicator !!!
test[:4]

PassengerId  Pclass                              Name     Sex   Age  SibSp  \
0          892       3                  Kelly, Mr. James    male  34.5      0   
1          893       3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2          894       2         Myles, Mr. Thomas Francis    male  62.0      0   
3          895       3                  Wirz, Mr. Albert    male  27.0      0   

   Parch  Ticket    Fare Cabin Embarked  IsFemale  
0      0  330911  7.8292   NaN        Q         0  
1      0  363272  7.0000   NaN        S         1  
2      0  240276  9.6875   NaN        Q         0  
3      0  315154  8.6625   NaN        S         0

In [22]:
# how many records in the training data set?
train.shape

(891, 12)

In [29]:
# how many people survived in the training set?
train.Survived.values.sum()

342

In [34]:
# what percentage of the training set survived?
train.Survived.values.sum() / train.shape[0]

0.3838383838383838

__NOTE__: Since we know that 38.3% of the people in the training set survived, we could achieve a training model accuracy of (1 - .383) = 61.7% by simply predicting "Did not survive" for each passenger. This metric is referred to as the __null error rate__.  When evaluating the performance of a binary logistic regression model, always check to see whether the accuracy you are attaining exceeds the __null error rate__. If not, your model is unlikely to be of any value.


Missing data will generally prevent the fitting of a model via either __scikit-learn__ or __statsmodels__, so we must first check both the training and testing data for missing data values:

In [4]:
# check the training data for null values
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Within the training data, the __Age__, __Cabin__ and __Embarked__ attributes all have missing data.

In [5]:
# check the test data for null values
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

Within the testing data, the __Age__, __Fare__ and __Cabin__  attributes all have missing data.

So if we want to use __Age__ as part of our predictive model, we need to somehow fill the missing __Age__ values. In this instance, the author of the PfDA text chooses to use the relatively simple process of filling the missing values with the __median__ Age value found within the __training__ data set:

In [4]:
# find the median 'Age' value within the training data set
impute_value = train['Age'].median()

# now fill the missing 'Age' values in both the training and testing data sets
train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

Next, __we create a dummy indicator for the 'Sex' categorical variable__: the new dummy variable 'IsFemale' contains a '1' if the 'Sex' value for a passenger is 'Female' and a '0' otherwise:

In [5]:
# create a dummy variable for the 'Sex' attribute in both the training and
# testing data sets
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

Now we are ready to define our predictive model using the attributes we want to use as explanatory variables:

In [6]:
# define a vector containing the names of the attributes to use
predictors = ['Pclass', 'IsFemale', 'Age']

# create a subset of the training data using ONLY the selected explanatory variables
X_train = train[predictors].values

# create a subset of the testing data using ONLY the selected explanatory variables
X_test = test[predictors].values

# isolate the response indicator for the training data
y_train = train['Survived'].values

# sanity check on training data
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [7]:
# sanity check on response indicator
y_train[:5]

array([0, 1, 1, 1, 0], dtype=int64)

In [7]:
# We're using the LogisticRegression() method for this model
model = LogisticRegression()

# fit the model: X_train contains our explanatory variables while 
# y_train contains the response variable
model.fit(X_train, y_train)

C:\Users\James T\Anaconda3\envs\DAV5400\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
# calculate the accuracy of the model relative to the training data set
model.score(X_train, y_train)

0.7946127946127947

Recall from above we calculated the __null error rate__ for our data to be 61.7%. The model we've generated has an accuracy score of 79.46%. As such, our model appears to be useful.

__What can we learn by examining the regression model coefficients for the explanatory variables?__

While the actual numeric values of the coefficients of a regression model are often very difficult to interpret, we can use the fact that a coefficient is either positive or negative to determine what effect of an __increase__ in the value of a given variable will have on the predicted value of the response variable. 

In this binary logistic regression example, the value of the response variable is the "log odds" of the binary outcome being either a '0' or '1' ('0' meaning the passenger was more likely to perish while '1' indicates the passenger was more likely to survive).

In [9]:
# examine the model coefficients for the explanatory variables
print(predictors)
model.coef_

['Pclass', 'IsFemale', 'Age']


array([[-1.07373582,  2.52093733, -0.02864864]])

From the above we see that:

- __Passenger Class__: An increase in the value of 'Passenger_Class' is associated with a __decreased__ likelihood of survival, i.e., passengers in lower classes of service were more likely to perish than were passengers in relatively higher classes of service.


- __IsFemale__: Being female increased the likelihood of survival


- __Age__: The older the passenger, the less likely they were to survive.

In [19]:
# generate predictions for the test data using our new model
y_predict = model.predict(X_test)
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

The 'y_predict' array contains predictions that answer the question: "__Was a given passenger more likely than not to have survived the sinking of the Titanic?__"

If we had the actual __survived/perished__ indicators for the test data, we could now check the performance of the model via a variety of error metrics (e.g., accuracy, specificity, precision, recall, AUC, etc.).

### Case Study: Logistic Regression with scikit-learn

https://nbviewer.jupyter.org/gist/justmarkham/6d5c061ca5aee67c4316471f8c2ae976